language: node_js
node_js:
  - "node"
cache: npm
script: npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: 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
  local_dir: dist
  on:
    branch: master